site_name: Pinball Power-Up Controller & DMD
site_url: https://ppuc.github.io/docs/
site_description: Pinball Power-Up Controller & DMD (PPUC) is a free and open-source pinball controller and display system.
use_directory_urls: true
repo_url: https://github.com/PPUC
repo_name: PPUC on GitHub
edit_uri: dosc/blob/main/docs/
docs_dir: docs

plugins:
  - search
  - github_repos:
      organization: PPUC
      cache_minutes: 30
      github_token: ""  # Only needed for private repos
      exclude_repos:
        - dmd
        - docs
        - .github
        - ZeDMD_Updater
        - ColorizingDMD
        - pindmd3-firmware
        - libppuclogger
      include_archived: false  # Whether to show archived repos
      forked_repos:
        - dmd-extensions
        - pinmame
        - libdmdutil

extra_css:
  - stylesheets/ppuc.css

markdown_extensions:
  - toc:
      title: On this page
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: includes
      check_paths: true
      auto_append:
        - content_footer.md
  - pymdownx.keys
  - pymdownx.extra

theme:
  name: material
  logo: /docs/images/logo.png
  icon:
    repo: fontawesome/brands/github
    edit: fontawesome/solid/wand-magic-sparkles
  custom_dir: overrides

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - toc.follow
    - content.code.annotate

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
    code: Noto Sans Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PPUC
      name: PPUC Organization
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fkkk4MbBn5
      name: Join our Discord
  base_url: /docs/

nav:
  - Overview: index.md
  - PPUC:
    - ppuc/index.md
    - ppuc/getting_started.md
    - ppuc/config_tool.md
    - ppuc/build_from_source.md
  - "PPUC Hardware":
    - ppuc_hardware/index.md
    - ppuc_hardware/io_16_8_1.md
    - ppuc_hardware/io_16x8_matrix.md
    - ppuc_hardware/out_8x10.md
    - ppuc_hardware/opto_16.md
  - ZeDMD:
    - zedmd/index.md
  - GitHub Repositories: github_repos.md
